config/routes.rb
Rails.application.routes.draw do

  get 'posts/new'
  get 'posts/create'
  get 'posts/show'
  get 'posts/index'
  get 'comments/new'
  get 'comments/create'
  get 'comments/show'
  root to: 'posts#index'
  resources :posts, only: [:new, :create, :index, :show] do
    resources :comments, only: [:new, :show, :create]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/application_resource.rb
class ApplicationResource <  ActiveResource::Base
  self.site = ENV['API_SERVER']
  self.include_format_in_path = false

  def save(options={})
    begin
      super
    rescue ActiveResource::ForbiddenAccess => ex
      errors = JSON.parse(ex.response.body)['errors']
      parse_and_set_errors(errors)
      false
    end
  end

  def parse_and_set_errors(errors)
    errors.each do |error|
      parse_and_set_error(error)
    end
  end

  # "'title' must be present"
  def parse_and_set_error(field)
    matchers = field.match(/\'([A-Za-z]+)\'\s(.*)/)
    return if matchers.nil?
    field_name = matchers[1]
    error_message = matchers[2]
    self.errors.add(field_name, error_message)

  end
end

app/models/resource/comment.rb
class Resource::Comment < ::ApplicationResource
  self.site = "#{ENV['API_SERVER']}/posts/:post_id/"

  before_validation :validate_attributes

  def post
    Resource::Post.find(self.prefix_options[:post_id])
  end

  def post=(post)
    self.prefix_options[:post_id] = post.id
  end

  def post_id=(post_id)
    self.prefix_options[:post_id] = post_id
  end

  def validate_attributes
    self.errors.add("name", "must be present") if self.attributes[:name].blank?
    self.errors.add("body", "must be present") if self.attributes[:body].blank?
  end
end

app/models/resource/post.rb
class Resource::Post < ::ApplicationResource
  before_validation :validate_attributes


  def comments(scope = :all)
    Resource::Comment.find(scope, :params => {:post_id => self.id})
  end

  protected

  def validate_attributes
    self.errors.add("title", "must be present") if self.attributes[:title].blank?
    self.errors.add("body", "must be present") if self.attributes[:body].blank?
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from ActiveResource::ServerError, with: :server_error

  def server_error(ex)
    flash[:error] = "Server error with: #{ex.message}"
    redirect_to root_url
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :load_post

  def new
    @comment = Resource::Comment.new(name: '', body: '')
  end

  def create
    @comment = Resource::Comment.new(filter_params)
    @comment.post = @post

    if @comment.valid? &&  @comment.save
      redirect_to post_path(params[:post_id]), notice: 'Comment created successfully'
    else
      flash.now[:error] = "Failed to create comment"
      render :new
    end
  end

  def filter_params
    params.require(:resource_comment).permit(:name, :body)
  end

  def load_post
    @post = Resource::Post.find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Resource::Post.new(title: '', body: '')
  end

  def create
    @post = Resource::Post.new(filter_params)
    if @post.valid? &&  @post.save
      redirect_to posts_path, notice: 'Post created successfully'
    else
      flash.now[:error] = "Failed to create post"
      render :new
    end
  end

  def show
    @post = Resource::Post.find(params[:id])
    @comments = @post.comments
  end

  def index
    @posts = Resource::Post.all
  end

  def filter_params
    params.require(:resource_post).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/create.html.slim
h1 Comments#create
p Find me in app/views/comments/create.html.slim

app/views/comments/new.html.slim
h1 class="font-bold font-sans break-normal text-gray-900 pt-6 pb-2 text-3xl md:text-4xl" = "Create a comment for: #{@post.title}"

div
  = form_for @comment, url: post_comments_path(post_id: params[:post_id]) , class: 'bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4' do |f|
    div class="mb-6"
      = f.label :name, class: "block text-gray-700 text-sm font-bold mb-2"
      = f.text_field :name, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
      p class="text-red-500 text-xs italic" = @comment.errors['name'].first

    div class="mb-6"
      = f.label :body, class: "block text-gray-700 text-sm font-bold mb-2"
      = f.text_area :body, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
      p class="text-red-500 text-xs italic" =  @comment.errors['body'].first


    div class="mb-6"
      = f.submit "Save", class: 'bg-transparent hover:bg-blue-500 text-blue-700 font-semibold hover:text-white py-2 px-4 border border-blue-500 hover:border-transparent rounded'

app/views/comments/show.html.slim
h1 Comments#show
p Find me in app/views/comments/show.html.slim

app/views/layouts/_flash_messages.html.erb
<% flash.each do |type, msg| %>
  <% css_class = type == 'notice' ? 'bg-green-100 border border-green-400 text-green-700' : 'bg-red-100 border border-red-400 text-red-700' %>
  <div class=" px-4 py-3 rounded relative <%=css_class%>" role="alert">
    <strong class="font-bold"><%=type.upcase %>!!!</strong>
    <span><%=msg%></span>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogClient</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://unpkg.com/tailwindcss/dist/tailwind.min.css" rel="stylesheet" />

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  
<body class="bg-gray-100 font-sans leading-normal tracking-normal">

	<nav id="header" class="fixed w-full z-10 top-0">

		<div id="progress" class="h-1 z-20 top-0" style="background:linear-gradient(to right, #4dc0b5 var(--scroll), transparent 0);"></div>

		<div class="w-full md:max-w-4xl mx-auto flex flex-wrap items-center justify-between mt-0 py-3">

			<div class="pl-4">
				<%= link_to 'SampleBlog', root_path, class: "text-gray-900 text-base no-underline hover:no-underline font-extrabold text-xl" %>
			</div>

			<div class="block lg:hidden pr-4">
				<button id="nav-toggle" class="flex items-center px-3 py-2 border rounded text-gray-500 border-gray-600 hover:text-gray-900 hover:border-green-500 appearance-none focus:outline-none">
					<svg class="fill-current h-3 w-3" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
						<title>Menu</title>
						<path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z" />
					</svg>
				</button>
			</div>


			<div class="w-full flex-grow lg:flex lg:items-center lg:w-auto hidden lg:block mt-2 lg:mt-0 bg-gray-100 md:bg-transparent z-20" id="nav-content">
				<ul class="list-reset lg:flex justify-end flex-1 items-center">
					<li class="mr-3">
					  <%= link_to "Create Post", new_post_path, class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %>
					</li>

					<li class="mr-3">
					  <%= link_to "Blogs", posts_path, class: "inline-block py-2 px-4 text-gray-900 font-bold no-underline" %>
					</li>
				</ul>
			</div>
		</div>
	</nav>

	<!--Container-->
	<div class="container w-full md:max-w-3xl mx-auto pt-20">

		<div class="w-full px-4 md:px-6 text-xl text-gray-800 leading-normal" style="font-family:Georgia,serif;">
			<%= render 'layouts/flash_messages' %>

			<%= yield %>
		</div>

	<script>
		/* Progress bar */
		//Source: https://alligator.io/js/progress-bar-javascript-css-variables/
		var h = document.documentElement,
			b = document.body,
			st = 'scrollTop',
			sh = 'scrollHeight',
			progress = document.querySelector('#progress'),
			scroll;
		var scrollpos = window.scrollY;
		var header = document.getElementById("header");
		var navcontent = document.getElementById("nav-content");

		document.addEventListener('scroll', function() {

			/*Refresh scroll % width*/
			scroll = (h[st] || b[st]) / ((h[sh] || b[sh]) - h.clientHeight) * 100;
			progress.style.setProperty('--scroll', scroll + '%');

			/*Apply classes for slide in bar*/
			scrollpos = window.scrollY;

			if (scrollpos > 10) {
				header.classList.add("bg-white");
				header.classList.add("shadow");
				navcontent.classList.remove("bg-gray-100");
				navcontent.classList.add("bg-white");
			} else {
				header.classList.remove("bg-white");
				header.classList.remove("shadow");
				navcontent.classList.remove("bg-white");
				navcontent.classList.add("bg-gray-100");

			}

		});


		//Javascript to toggle the menu
		document.getElementById('nav-toggle').onclick = function() {
			document.getElementById("nav-content").classList.toggle("hidden");
		}
	</script>

</body>

</html>

app/views/posts/create.html.slim
h1 Posts#create
p Find me in app/views/posts/create.html.slim

app/views/posts/index.html.slim
h1 class="font-bold font-sans break-normal text-gray-900 pt-6 pb-2 text-3xl md:text-4xl" Welcome to our blogs


- if @posts.empty?
- else
  div
    - @posts.each do |post|
      h2 class="font-bold font-sans break-normal text-gray-900 pt-6 pb-2 text-3xl md:text-2xl" = post.title
      p class="text-sm md:text-base font-normal text-gray-600" = "Published #{post.created_at}"
      p.py-6 
        = truncate(post.body, length: 200)
        = link_to "Read more ...", post_path(post), class: 'text-base md:text-sm text-green-500 font-bold no-underline hover:underline'

app/views/posts/new.html.slim
h1 class="font-bold font-sans break-normal text-gray-900 pt-6 pb-2 text-3xl md:text-4xl" Create a Post
br

div
  = form_for @post, url: :posts, class: 'bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4' do |f|
    div class="mb-6"
      = f.label :title, class: "block text-gray-700 text-sm font-bold mb-2"
      = f.text_field :title, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
      p class="text-red-500 text-xs italic" = @post.errors['title'].first

    div class="mb-6"
      = f.label :body, class: "block text-gray-700 text-sm font-bold mb-2"
      = f.text_area :body, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
      p class="text-red-500 text-xs italic" =  @post.errors['body'].first


    div class="mb-6"
      = f.submit "Save", class: 'bg-transparent hover:bg-blue-500 text-blue-700 font-semibold hover:text-white py-2 px-4 border border-blue-500 hover:border-transparent rounded'

app/views/posts/show.html.slim
h1 class="font-bold font-sans break-normal text-gray-900 pt-6 pb-2 text-3xl md:text-4xl" = @post.title
p class="text-sm md:text-base font-normal text-gray-600" = "Published #{@post.created_at}"

p.py-6 = @post.body


h2 class="font-bold font-sans break-normal text-gray-900 pt-6 pb-2 text-xl md:text-2xl" Comments
- if @comments.empty?
  p Be the first to make comment

- else
  div
    - @comments.each do |comment|
      h3 class="font-bold font-sans break-normal text-gray-900 pt-6 pb-2 text-xl md:text-1xl" = comment.name
      p class="text-sm md:text-base font-normal text-gray-600" = "Commented at #{comment.created_at}"

      p.py-6 = comment.body

p.py-6 = link_to "Create comment", new_post_comment_path(post_id: @post.id), class: 'bg-transparent hover:bg-blue-500 text-blue-700 font-semibold hover:text-white py-2 px-4 border border-blue-500 hover:border-transparent rounded'